{% set name = "autodataman" %}
{% set version = "0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cmecmetrics/autodataman/archive/refs/tags/{{ version }}.tar.gz
  sha256: 5d1c2b6ab28279fdf918b812a390675915778316f3eeb205ce785bbb0c7ff576

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - autodataman = autodataman.autodataman:main
    - adm = autodataman.autodataman:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - requests

test:
  imports:
    - autodataman
  commands:
    - autodataman --help

about:
  home: https://github.com/cmecmetrics/autodataman
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Autodataman
  description: |
    The autodataman tool is intended to be a very lightweight climate data database and data distribution engine.
  doc_url: https://github.com/cmecmetrics/autodataman/tree/ao_python#readme
  dev_url: https://github.com/cmecmetrics/autodataman

extra:
  recipe-maintainers:
    - acordonez
    - paullric
